[build]
  command = "npm ci"
  publish = "Bingo Web"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  node_version = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
