[build]
  command = "npm install"
  publish = "Bingo Web"
  functions = "api"

[functions]
  # Usamos esbuild para ESM y mejor tree-shaking
  node_bundler = "esbuild"
  # Forzamos Node 18+ en funciones (Blobs lo requiere)
  node_version = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
