[functions]
node_bundler = "esbuild"
external_node_modules = ["@netlify/functions", "@netlify/blobs"]

[build]
functions = "netlify/functions"
publish = "."

[dev]
functions = "netlify/functions"

[functions.environment]
NODE_VERSION = "20"
