[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"

# --- LÍNEAS NUEVAS Y CRÍTICAS ---
# Esto le ordena a Netlify preparar (provisionar) un almacén de Blobs
# llamado "cartones-venta" cuando despliegues el sitio.
[[blobs]]
  store_name = "cartones-venta"
# --- FIN DE LAS LÍNEAS NUEVAS ---

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200