[build]
  command = "npm install"
  publish = "Bingo Web"
  # CORRECCIÓN FINAL: Le decimos a Netlify la ruta real de tus funciones
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200