# ======================================================
# CONFIGURACIÓN DE CONSTRUCCIÓN Y DESPLIEGUE
# ======================================================
[build]
  # El directorio que contiene tu sitio público (index.html, etc.)
  publish = "Bingo Web/"
  
  # El directorio que contiene tus funciones de Netlify
  functions = "netlify/"

# Configuración específica de las funciones
[functions]
  node_bundler = "esbuild"

# ======================================================
# REGLA DE REDIRECCIÓN PARA LA API
# ======================================================
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200